name: Node.js CI & Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Archive artifact
        run: tar -czf artifact.tar.gz build/  # Adjust if needed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: artifact.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts

      - name: Copy artifact to VM at UAT location
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          scp -i ~/.ssh/id_rsa artifact.tar.gz $VM_USER@$VM_HOST:/opt/chassio-web/uat

      - name: Deploy on VM
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa $VM_USER@$VM_HOST << 'EOF'
          cd /opt/chassio-web/uat
          tar -xzf artifact.tar.gz
          pm2 stop all || true  # Stop running process (if any)
          pm2 start build/index.js  # Adjust entry point if needed
          EOF
